export const BATHROOM_CASE_STUDY_IMAGES = [
  {
    key: 'before',
    src: '/Portfolio/bathroom-renovation-east-london-before.webp',
    alt: 'Original bathroom before East London bathroom renovation',
    label: 'Before',
    caption: 'Original bathroom before the renovation, with dated finishes and a layout ready for improvement.',
  },
  {
    key: 'stripped-prep',
    src: '/Portfolio/bathroom-renovation-east-london-stripped-prep.webp',
    alt: 'Bathroom stripped out before waterproofing and new installation',
    label: 'During Prep',
    caption: 'Bathroom stripped back before preparation, waterproofing and the new installation.',
  },
  {
    key: 'waterproofing-tile-prep',
    src: '/Portfolio/bathroom-renovation-east-london-waterproofing-tile-prep.webp',
    alt: 'Waterproofing and preparation stage before tiling in walk-in shower bathroom',
    label: 'Waterproofing',
    caption: 'Waterproofing and preparation stage before the final tiling and bathroom installation.',
  },
  {
    key: 'shower-niche-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-shower-niche.webp',
    alt: 'Walk-in shower niche with large-format tiling and matte black fittings',
    label: 'Detail',
    caption: 'Bathroom lighting, tiling and fittings were selected for a clean look and practical daily use.',
  },
  {
    key: 'tile-drain-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-tile-drain-detail.webp',
    alt: 'Large-format bathroom tiles and wall-mounted shower fittings',
    label: 'Tiling',
    caption: 'Large-format tiling, shower glass and drainage details helped keep the bathroom practical and easy to maintain.',
  },
  {
    key: 'floating-oak-vanity',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-floating-oak-vanity.webp',
    alt: 'LED mirror and floating vanity in finished bathroom renovation',
    label: 'Vanity',
    caption: 'Clean mirror, lighting and vanity details helped the bathroom feel more complete.',
  },
  {
    key: 'backlit-mirror-lighting',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-backlit-mirror.webp',
    alt: 'LED mirror and floating vanity with wall-mounted taps after bathroom renovation',
    label: 'Lighting',
    caption: 'Storage and wall-mounted fittings kept the vanity area practical and uncluttered.',
  },
  {
    key: 'storage-toilet-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-storage-toilet-detail.webp',
    alt: 'Walk-in shower and practical bathroom storage after renovation',
    label: 'Storage',
    caption: 'Built-in storage and wall-mounted fittings kept the bathroom practical and uncluttered.',
  },
  {
    key: 'final-wide-shot',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-wide-shot.webp',
    alt: 'Finished walk-in bathroom renovation in East London with floating vanity and LED mirror',
    label: 'After',
    caption: 'Clean completed bathroom with walk-in shower, double vanity and warm neutral finishes.',
  },
  {
    key: 'final-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-final-detail.webp',
    alt: 'Finished East London bathroom renovation with clean tiling and modern fittings',
    label: 'Final Detail',
    caption: 'Final tiling, lighting and shower details created a cleaner, more modern finish.',
  },
]
