export const BATHROOM_CASE_STUDY_IMAGES = [
  {
    key: 'before',
    src: '/Portfolio/bathroom-renovation-east-london-before.webp',
    alt: 'Bathroom before renovation in East London',
    label: 'Before',
    caption: 'Original bathroom before the renovation, with dated finishes and a layout ready for improvement.',
  },
  {
    key: 'stripped-prep',
    src: '/Portfolio/bathroom-renovation-east-london-stripped-prep.webp',
    alt: 'Bathroom stripped out during preparation stage in East London',
    label: 'During Prep',
    caption: 'Bathroom stripped back ready for preparation, setting out and first-fix checks.',
  },
  {
    key: 'waterproofing-tile-prep',
    src: '/Portfolio/bathroom-renovation-east-london-waterproofing-tile-prep.webp',
    alt: 'Bathroom waterproofing and tile preparation stage in East London',
    label: 'Waterproofing',
    caption: 'Waterproofing, backer boards and tile preparation completed before final finishes.',
  },
  {
    key: 'shower-niche-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-shower-niche.webp',
    alt: 'Clean finished shower niche with warm lighting and black brassware',
    label: 'Detail',
    caption: 'Clean recessed shower niche finished with warm lighting and sharp tile edges.',
  },
  {
    key: 'floating-oak-vanity',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-floating-oak-vanity.webp',
    alt: 'Clean finished floating oak vanity with twin basins and matte black wall taps',
    label: 'Vanity',
    caption: 'Clean handover shot of the floating oak vanity, twin basins and wall-mounted taps.',
  },
  {
    key: 'backlit-mirror-lighting',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-backlit-mirror.webp',
    alt: 'Clean backlit bathroom mirror and vanity lighting after fitting',
    label: 'Lighting',
    caption: 'Backlit mirror, twin basins and crisp wall finish photographed before styling.',
  },
  {
    key: 'final-wide-shot',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-wide-shot.webp',
    alt: 'Clean completed East London bathroom renovation wide shot after fitting',
    label: 'After',
    caption: 'Clean completed bathroom with walk-in shower, double vanity and warm neutral finishes.',
  },
  {
    key: 'final-detail',
    src: '/Portfolio/bathroom-renovation-east-london-clean-handover-final-detail.webp',
    alt: 'Clean completed bathroom vanity and shower finishing detail',
    label: 'Final Detail',
    caption: 'Final handover detail showing clean junctions, black brassware and warm material tones.',
  },
]
