import { CalendarCheck, ChevronLeft, ChevronRight, CircleDollarSign, ClipboardCheck, KeyRound, MapPin, PackageCheck, Search } from 'lucide-react'
import { addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, parseISO, startOfMonth, startOfWeek, subMonths, subWeeks } from 'date-fns'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useJobManager } from '../context/JobManagerContext'
import { formatDate } from '../utils/format'
import { PageHeader } from '../components/UI'

const iconMap = { Work: CalendarCheck, 'Site visit': Search, 'Key collection': KeyRound, Payment: CircleDollarSign, Materials: PackageCheck, Inspection: ClipboardCheck, Handover: ClipboardCheck }
const toDate = (value) => parseISO(value)

export default function CalendarPage() {
  const { data } = useJobManager(); const [view, setView] = useState('month'); const [cursor, setCursor] = useState(parseISO('2026-07-18'))
  const events = useMemo(() => [...data.events, ...data.payments.filter((payment) => payment.status !== 'Paid').map((payment) => { const project = data.projects.find((item) => item.id === payment.projectId); const client = data.clients.find((item) => item.id === project.clientId); return { id: `calendar-${payment.id}`, projectId: project.id, type: 'Payment', title: `${client.name.split(' ')[0]} – ${project.postcode}`, startDate: payment.dueDate, endDate: payment.dueDate, allDay: true, location: project.address, notes: payment.title, colourCategory: 'red' } })], [data])
  const interval = view === 'month' ? { start: startOfWeek(startOfMonth(cursor), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(cursor), { weekStartsOn: 1 }) } : { start: startOfWeek(cursor, { weekStartsOn: 1 }), end: endOfWeek(cursor, { weekStartsOn: 1 }) }
  const days = eachDayOfInterval(interval)
  const eventForDay = (event, day) => { const start = toDate(event.startDate); const end = toDate(event.endDate || event.startDate); const d = format(day, 'yyyy-MM-dd'); return d >= format(start, 'yyyy-MM-dd') && d <= format(end, 'yyyy-MM-dd') }
  const move = (direction) => setCursor((date) => view === 'month' ? (direction > 0 ? addMonths(date, 1) : subMonths(date, 1)) : (direction > 0 ? addWeeks(date, 1) : subWeeks(date, 1)))
  return <>
    <PageHeader eyebrow="Europe / London" title="Calendar" description="Work, visits, keys, materials and deadlines in one schedule." />
    <div className="jm-calendar-toolbar"><div><button onClick={() => move(-1)} aria-label="Previous"><ChevronLeft size={20} /></button><button onClick={() => setCursor(parseISO('2026-07-18'))}>Today</button><button onClick={() => move(1)} aria-label="Next"><ChevronRight size={20} /></button><h2>{view === 'month' ? format(cursor, 'MMMM yyyy') : `${format(interval.start, 'd MMM')} – ${format(interval.end, 'd MMM yyyy')}`}</h2></div><div className="jm-segment"><button className={view === 'month' ? 'active' : ''} onClick={() => setView('month')}>Month</button><button className={view === 'week' ? 'active' : ''} onClick={() => setView('week')}>Week</button></div></div>
    <div className="jm-calendar-legend"><span><i className="green" />Work</span><span><i className="blue" />Visits & keys</span><span><i className="yellow" />Provisional</span><span><i className="red" />Payments & urgent</span><span><i className="orange" />Materials</span><span><i className="grey" />Completed</span></div>
    {view === 'month' ? <div className="jm-calendar-month"><div className="jm-weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day) => <span key={day}>{day}</span>)}</div><div className="jm-month-grid">{days.map((day) => { const dayEvents = events.filter((event) => eventForDay(event, day)); return <div key={day.toISOString()} className={`${!isSameMonth(day, cursor) ? 'outside' : ''} ${isSameDay(day, parseISO('2026-07-18')) ? 'today' : ''}`}><span className="jm-day-number">{format(day, 'd')}</span><div className="jm-day-events">{dayEvents.slice(0, 3).map((event) => <CalendarEvent key={event.id} event={event} compact />)}{dayEvents.length > 3 && <small>+{dayEvents.length - 3} more</small>}</div></div> })}</div></div> : <div className="jm-calendar-week">{days.map((day) => { const dayEvents = events.filter((event) => eventForDay(event, day)); return <section key={day.toISOString()} className={isSameDay(day, parseISO('2026-07-18')) ? 'today' : ''}><header><span>{format(day, 'EEE')}</span><strong>{format(day, 'd')}</strong></header><div>{dayEvents.length ? dayEvents.map((event) => <CalendarEvent key={event.id} event={event} />) : <p>No events</p>}</div></section> })}</div>}
    <section className="jm-calendar-agenda"><h2>Next scheduled items</h2>{events.filter((event) => event.startDate.slice(0, 10) >= '2026-07-18').sort((a, b) => a.startDate.localeCompare(b.startDate)).slice(0, 6).map((event) => { const Icon = iconMap[event.type] || CalendarCheck; return <Link key={event.id} to={`/job-manager/projects/${event.projectId}`}><span className={`jm-agenda-icon jm-agenda-icon--${event.colourCategory}`}><Icon size={18} /></span><div><strong>{event.title}</strong><span>{event.type}{event.notes ? ` · ${event.notes}` : ''}</span></div><div><strong>{formatDate(event.startDate, !event.allDay)}</strong><span><MapPin size={13} />{event.location}</span></div></Link> })}</section>
  </>
}

function CalendarEvent({ event, compact = false }) { const Icon = iconMap[event.type] || CalendarCheck; return <Link title={`${event.type}: ${event.title}`} to={`/job-manager/projects/${event.projectId}`} className={`jm-calendar-event jm-calendar-event--${event.colourCategory}`}>{!compact && <Icon size={15} />}<span>{event.title}</span>{!compact && <small>{event.type}</small>}</Link> }
