import { ArrowLeft, CalendarPlus, CheckCircle2, CirclePoundSterling, Clock3, ExternalLink, Mail, MapPin, MessageSquarePlus, Phone, Plus, Save, Trophy, UserRound, XCircle } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import LeadFilesPanel from '../components/LeadFilesPanel'
import { EmptyState } from '../components/UI'
import { useJobManager } from '../context/JobManagerContext'
import { formatDate, formatGBP, londonDateKey, mapsUrl } from '../utils/format'
import { leadStages } from '../utils/leads'

export default function LeadDetailPage() {
  const { id } = useParams(); const navigate = useNavigate()
  const { data, users, user, authMode, saveLead, updateLeadStage, logLeadCommunication, addLeadTask, bookLeadVisit, markLeadLost, uploadLeadDocument, uploadLeadQuote, attachLeadQuoteDocument, selectLeadQuote, deleteDocument, convertLead } = useJobManager()
  const lead = data.leads.find((item) => item.id === id)
  const [edit, setEdit] = useState(false); const [form, setForm] = useState(lead || {}); const [dialog, setDialog] = useState(''); const [busy, setBusy] = useState(false)
  if (!lead) return <EmptyState title="Lead not found" text="It may have been archived or removed." action={<Link className="jm-button" to="/job-manager/leads">Back to leads</Link>} />

  const communications = data.leadCommunications.filter((item) => item.leadId === id).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt))
  const tasks = data.tasks.filter((item) => item.leadId === id); const events = data.events.filter((item) => item.leadId === id); const activities = data.activities.filter((item) => item.leadId === id)
  const documents = data.documents.filter((item) => item.leadId === id); const quotes = data.leadQuotes.filter((item) => item.leadId === id).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); const selectedQuote = quotes.find((item) => item.id === lead.quoteId) || quotes[quotes.length - 1]
  const save = async () => { setBusy(true); try { await saveLead(form, id); setEdit(false) } finally { setBusy(false) } }

  const submitDialog = async (values) => {
    setBusy(true)
    try {
      if (dialog === 'communication') await logLeadCommunication(id, values)
      if (dialog === 'task') await addLeadTask(id, values)
      if (dialog === 'visit') await bookLeadVisit(id, values)
      if (dialog === 'lost') await markLeadLost(id, values)
      if (dialog === 'convert') { const projectId = await convertLead(id, values); navigate(`/job-manager/projects/${projectId}`) }
      setDialog('')
    } finally { setBusy(false) }
  }

  return <>
    <Link className="jm-back-link" to="/job-manager/leads"><ArrowLeft size={16} />Back to leads</Link>
    <header className="jm-lead-header jm-lead-header--premium">
      <div className="jm-lead-identity"><div className="jm-lead-title-line"><p className="jm-eyebrow">{lead.source} enquiry</p><span className={`jm-priority-pill jm-priority-${lead.priority.toLowerCase()}`}>{lead.priority}</span></div><h1>{lead.clientName}</h1><p>{lead.projectType} <span>·</span> {lead.postcode || 'No postcode'}</p></div>
      <div className="jm-lead-commercial"><div className="jm-lead-hero-stats"><span><small>Pipeline stage</small><strong>{lead.stage}</strong></span><span><small>Selected quote</small><strong>{selectedQuote ? formatGBP(selectedQuote.amount || 0) : 'Not configured'}</strong></span><span><small>Documents</small><strong>{documents.length} file{documents.length === 1 ? '' : 's'}</strong></span></div><div className="jm-lead-header-actions"><select aria-label="Lead stage" value={lead.stage} onChange={(event) => updateLeadStage(id, event.target.value)}>{leadStages.filter((item) => user.role === 'administrator' || !['Won', 'Lost', 'Archived', 'Quote Preparing', 'Quote Sent', 'Negotiation'].includes(item)).map((item) => <option key={item}>{item}</option>)}</select><button className="jm-button" onClick={() => setEdit(!edit)}>{edit ? 'Cancel edit' : 'Edit lead'}</button>{user.role === 'administrator' && !lead.convertedProjectId && <button className="jm-button jm-button--won" onClick={() => setDialog('convert')}><Trophy size={17} />Won job</button>}</div></div>
    </header>
    {lead.convertedProjectId && <div className="jm-success-banner"><CheckCircle2 size={18} />Converted to a project. <Link to={`/job-manager/projects/${lead.convertedProjectId}`}>Open project</Link></div>}
    <section className="jm-lead-actionbar"><span>Quick actions</span><div className="jm-lead-quick-actions"><a className={!lead.phone ? 'is-disabled' : ''} href={lead.phone ? `tel:${lead.phone}` : undefined}><Phone size={18} />Call</a><a className={!lead.email ? 'is-disabled' : ''} href={lead.email ? `mailto:${lead.email}` : undefined}><Mail size={18} />Email</a><button onClick={() => setDialog('communication')}><MessageSquarePlus size={18} />Log contact</button><button onClick={() => setDialog('visit')}><CalendarPlus size={18} />Book visit</button>{user.role === 'administrator' && <button onClick={() => setDialog('task')}><Plus size={18} />Add task</button>}</div></section>

    <div className="jm-lead-detail-grid"><main>
      <section className="jm-panel jm-lead-overview">
        <header><div><p className="jm-eyebrow">Opportunity brief</p><h2>Lead overview</h2></div>{edit && <button className="jm-button jm-button--primary" onClick={save} disabled={busy}><Save size={16} />Save changes</button>}</header>
        {edit ? <div className="jm-form-grid"><Field label="Client name" value={form.clientName} onChange={(value) => setForm({ ...form, clientName: value })} /><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} /><Field label="Postcode" value={form.postcode} onChange={(value) => setForm({ ...form, postcode: value })} /><Field label="Address" wide value={form.fullAddress} onChange={(value) => setForm({ ...form, fullAddress: value })} /><Field label="Next action" value={form.nextAction} onChange={(value) => setForm({ ...form, nextAction: value })} /><Field label="Next action due" type="datetime-local" value={form.nextActionDueAt?.slice(0, 16) || ''} onChange={(value) => setForm({ ...form, nextActionDueAt: value })} /><Field label="Enquiry summary" wide textarea value={form.enquirySummary} onChange={(value) => setForm({ ...form, enquirySummary: value })} /><Field label="Internal notes" wide textarea value={form.internalNotes} onChange={(value) => setForm({ ...form, internalNotes: value })} /></div> : <>
          <div className="jm-lead-fact-grid"><Fact icon={Phone} label="Contact" value={lead.phone || lead.email || 'No contact details'} note={lead.phone && lead.email ? lead.email : ''} /><Fact icon={MapPin} label="Property" value={lead.fullAddress || lead.postcode || 'Address not added'} note={lead.fullAddress ? lead.postcode : ''} /><Fact icon={CirclePoundSterling} label="Estimated value" value={formatGBP(lead.estimatedValue || 0)} /><Fact icon={UserRound} label="Owner" value={users.find((item) => item.id === lead.assignedTo)?.name || 'Unassigned'} /></div>
          <div className="jm-next-action-card"><span className="jm-next-action-icon"><Clock3 size={20} /></span><div><small>Next best action</small><strong>{lead.nextAction || 'Set the next follow-up'}</strong><span>{lead.nextActionDueAt ? `Due ${formatDate(lead.nextActionDueAt, true)}` : 'No due date set'}</span></div><button type="button" onClick={() => setEdit(true)}>Update</button></div>
          <div className="jm-lead-notes-grid"><section><span>Enquiry summary</span><p>{lead.enquirySummary || 'No enquiry summary has been added.'}</p></section><section><span>Internal notes</span><p>{lead.internalNotes || 'No internal notes yet.'}</p></section></div>
        </>}
      </section>
      <LeadFilesPanel lead={lead} quotes={quotes} documents={documents} users={users} storageEnabled={authMode === 'supabase'} canManageQuotes={user.role === 'administrator'} canDelete={(document) => user.role === 'administrator' || document.uploadedBy === user.id} onUploadQuote={(values, file) => uploadLeadQuote(id, values, file)} onAttachQuote={(values, documentId) => attachLeadQuoteDocument(id, values, documentId)} onUploadFiles={(values, file) => uploadLeadDocument(id, values, file)} onSelectQuote={(quoteId) => selectLeadQuote(id, quoteId)} onDelete={deleteDocument} />
      <section className="jm-panel jm-lead-timeline"><h2>Communications</h2>{communications.length ? communications.map((item) => <article key={item.id}><span>{item.type}</span><div><strong>{item.summary}</strong><p>{item.note}</p><small>{item.direction} · {formatDate(item.occurredAt, true)} · {users.find((entry) => entry.id === item.authorId)?.name}</small>{item.externalLink && <a href={item.externalLink} target="_blank" rel="noreferrer"><ExternalLink size={14} />Open link</a>}</div></article>) : <p className="jm-muted">No communication has been logged yet.</p>}</section>
      <section className="jm-panel"><h2>Tasks & site visits</h2><div className="jm-lead-records">{events.map((event) => <div key={event.id}><CalendarPlus size={18} /><span><strong>{event.title}</strong>{formatDate(event.startDate, true)} · {event.syncStatus === 'not_configured' ? 'Calendar sync not configured' : event.syncStatus}</span></div>)}{tasks.map((task) => <div key={task.id}><CheckCircle2 size={18} /><span><strong>{task.title}</strong>Due {formatDate(task.dueDate)} · {task.priority}</span></div>)}{!events.length && !tasks.length && <p className="jm-muted">No tasks or visits yet.</p>}</div></section>
    </main><aside>
      <section className="jm-panel jm-lead-contact"><p className="jm-eyebrow">Client details</p><h2>Contact & property</h2><ContactLink icon={Phone} label="Phone" value={lead.phone} href={lead.phone ? `tel:${lead.phone}` : ''} empty="No phone number" /><ContactLink icon={Mail} label="Email" value={lead.email} href={lead.email ? `mailto:${lead.email}` : ''} empty="No email address" /><ContactLink icon={MapPin} label="Location" value={lead.fullAddress || lead.postcode} href={mapsUrl(lead.fullAddress, lead.postcode)} external empty="No address added" /><div className="jm-contact-preference"><span>Preferred contact</span><strong>{lead.preferredContactMethod} · {lead.preferredContactTime || 'Any time'}</strong></div></section>
      <section className="jm-panel jm-lead-activity"><p className="jm-eyebrow">History</p><h2>Recent activity</h2><div className="jm-mini-activity">{activities.slice(0, 8).map((item) => <div key={item.id}><span /><div><strong>{item.action}</strong><small>{formatDate(item.createdAt, true)}</small></div></div>)}{!activities.length && <p className="jm-muted">No activity yet.</p>}</div></section>
      {user.role === 'administrator' && !lead.convertedProjectId && <section className="jm-panel jm-lead-controls jm-lead-controls--won"><Trophy size={25} /><h2>Did you win this job?</h2><p>The selected quote and every lead file will move into a new confirmed project.</p><button className="jm-button jm-button--won" onClick={() => setDialog('convert')}><Trophy size={17} />Won job · Create project</button><button className="jm-button jm-button--danger" onClick={() => setDialog('lost')}><XCircle size={17} />Mark lost</button></section>}
    </aside></div>
    {dialog && <LeadDialog type={dialog} lead={lead} quote={selectedQuote} users={users} close={() => setDialog('')} submit={submitDialog} busy={busy} />}
  </>
}

function LeadDialog({ type, lead, quote, users, close, submit, busy }) {
  const today = londonDateKey()
  const defaults = { communication: { type: 'Call', direction: 'Outbound', summary: '', note: '' }, task: { title: '', dueDate: '', priority: 'Normal', assignedTo: lead.assignedTo }, visit: { startDate: '', endDate: '', notes: '' }, lost: { reason: 'Price', notes: '' }, convert: { title: quote?.projectTitle || `${lead.projectType} - ${lead.clientName}`, startDate: quote?.startDate || today, endDate: quote?.endDate || quote?.startDate || today, assignedTo: lead.assignedTo, contractValue: quote?.amount || lead.estimatedValue || '' } }
  const [form, setForm] = useState(defaults[type]); const titles = { communication: 'Log communication', task: 'Add lead task', visit: 'Book site visit', lost: 'Mark lead as lost', convert: 'Won job · Create project' }
  return <div className="jm-modal-backdrop" onMouseDown={close}><section className="jm-modal jm-lead-dialog" onMouseDown={(event) => event.stopPropagation()}><header><h2>{titles[type]}</h2><button onClick={close}>×</button></header><form onSubmit={(event) => { event.preventDefault(); submit(form) }} className="jm-form-grid">
    {type === 'communication' && <><Select label="Type" value={form.type} options={['Call', 'Email', 'SMS', 'WhatsApp', 'Meeting', 'Note']} onChange={(value) => setForm({ ...form, type: value })} /><Select label="Direction" value={form.direction} options={['Inbound', 'Outbound', 'Internal']} onChange={(value) => setForm({ ...form, direction: value })} /><Field label="Summary" wide required value={form.summary} onChange={(value) => setForm({ ...form, summary: value })} /><Field label="Notes" wide textarea value={form.note} onChange={(value) => setForm({ ...form, note: value })} /></>}
    {type === 'task' && <><Field label="Task" wide required value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><Field label="Due date" type="date" required value={form.dueDate} onChange={(value) => setForm({ ...form, dueDate: value })} /><Select label="Priority" value={form.priority} options={['Low', 'Normal', 'High', 'Urgent']} onChange={(value) => setForm({ ...form, priority: value })} /></>}
    {type === 'visit' && <><Field label="Starts" type="datetime-local" required value={form.startDate} onChange={(value) => setForm({ ...form, startDate: value })} /><Field label="Ends" type="datetime-local" value={form.endDate} onChange={(value) => setForm({ ...form, endDate: value })} /><Field label="Visit notes" wide textarea value={form.notes} onChange={(value) => setForm({ ...form, notes: value })} /></>}
    {type === 'lost' && <><Select label="Reason" value={form.reason} options={['Price', 'No response', 'Chose competitor', 'Timing', 'Not suitable', 'Duplicate', 'Other']} onChange={(value) => setForm({ ...form, reason: value })} /><Field label="Notes" wide textarea value={form.notes} onChange={(value) => setForm({ ...form, notes: value })} /></>}
    {type === 'convert' && <><div className="jm-field-wide jm-won-summary"><Trophy size={21} /><div><strong>{quote ? `Using quote ${quote.reference || ''}` : 'No quote selected'}</strong><span>{quote ? `${formatGBP(quote.amount || 0)} · The quote PDF, files, tasks and visits will move to the project.` : 'The project will use the lead details. You can upload and select a quote first.'}</span></div></div><Field label="Project title" wide required value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><Field label="Start date" type="date" required value={form.startDate} onChange={(value) => setForm({ ...form, startDate: value })} /><Field label="End date" type="date" required value={form.endDate} onChange={(value) => setForm({ ...form, endDate: value })} /><Field label="Contract value (£)" type="number" value={form.contractValue} onChange={(value) => setForm({ ...form, contractValue: value })} /><Select label="Assigned to" value={form.assignedTo || ''} options={users.map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => setForm({ ...form, assignedTo: value })} /></>}
    <footer><button type="button" className="jm-button" onClick={close}>Cancel</button><button className={`jm-button ${type === 'lost' ? 'jm-button--danger' : type === 'convert' ? 'jm-button--won' : 'jm-button--primary'}`} disabled={busy}>{busy ? 'Saving…' : type === 'convert' ? 'Confirm won job' : 'Confirm'}</button></footer>
  </form></section></div>
}

function Fact({ icon: Icon, label, value, note }) { return <div className="jm-lead-fact"><span><Icon size={17} /></span><div><small>{label}</small><strong>{value}</strong>{note && <em>{note}</em>}</div></div> }
function ContactLink({ icon: Icon, label, value, href, external, empty }) { const content = <><span><Icon size={17} /></span><div><small>{label}</small><strong>{value || empty}</strong></div>{href && <ExternalLink size={14} />}</>; return href ? <a className="jm-lead-contact-row" href={href} target={external ? '_blank' : undefined} rel={external ? 'noreferrer' : undefined}>{content}</a> : <div className="jm-lead-contact-row is-empty">{content}</div> }
function Field({ label, wide, textarea, onChange, ...props }) { const Tag = textarea ? 'textarea' : 'input'; return <label className={wide ? 'jm-field-wide' : ''}><span>{label}</span><Tag {...props} onChange={(event) => onChange(event.target.value)} /></label> }
function Select({ label, options, onChange, ...props }) { return <label><span>{label}</span><select {...props} onChange={(event) => onChange(event.target.value)}>{options.map((item) => typeof item === 'string' ? <option key={item}>{item}</option> : <option key={item.value} value={item.value}>{item.label}</option>)}</select></label> }
