import { ArrowLeft, CalendarPlus, CheckCircle2, ExternalLink, Mail, MapPin, MessageSquarePlus, Phone, Plus, Save, Trophy, XCircle } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import LeadFilesPanel from '../components/LeadFilesPanel'
import { EmptyState } from '../components/UI'
import { useJobManager } from '../context/JobManagerContext'
import { formatDate, formatGBP, mapsUrl } from '../utils/format'
import { leadStages } from '../utils/leads'

export default function LeadDetailPage() {
  const { id } = useParams(); const navigate = useNavigate()
  const { data, users, user, authMode, saveLead, updateLeadStage, logLeadCommunication, addLeadTask, bookLeadVisit, markLeadLost, uploadLeadDocument, uploadLeadQuote, selectLeadQuote, deleteDocument, convertLead } = useJobManager()
  const lead = data.leads.find((item) => item.id === id)
  const [edit, setEdit] = useState(false); const [form, setForm] = useState(lead || {}); const [dialog, setDialog] = useState(''); const [busy, setBusy] = useState(false)
  if (!lead) return <EmptyState title="Lead not found" text="It may have been archived or removed." action={<Link className="jm-button" to="/job-manager/leads">Back to leads</Link>} />

  const communications = data.leadCommunications.filter((item) => item.leadId === id).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt))
  const tasks = data.tasks.filter((item) => item.leadId === id); const events = data.events.filter((item) => item.leadId === id); const activities = data.activities.filter((item) => item.leadId === id)
  const documents = data.documents.filter((item) => item.leadId === id); const quotes = data.leadQuotes.filter((item) => item.leadId === id).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); const selectedQuote = quotes.find((item) => item.id === lead.quoteId) || quotes[quotes.length - 1]
  const save = async () => { setBusy(true); try { await saveLead(form, id); setEdit(false) } finally { setBusy(false) } }

  const submitDialog = async (values) => {
    setBusy(true)
    try {
      if (dialog === 'communication') await logLeadCommunication(id, values)
      if (dialog === 'task') await addLeadTask(id, values)
      if (dialog === 'visit') await bookLeadVisit(id, values)
      if (dialog === 'lost') await markLeadLost(id, values)
      if (dialog === 'convert') { const projectId = await convertLead(id, values); navigate(`/job-manager/projects/${projectId}`) }
      setDialog('')
    } finally { setBusy(false) }
  }

  return <>
    <Link className="jm-back-link" to="/job-manager/leads"><ArrowLeft size={16} />Back to leads</Link>
    <header className="jm-lead-header jm-lead-header--premium">
      <div><div className="jm-lead-title-line"><p className="jm-eyebrow">{lead.source} enquiry</p><span className={`jm-priority-pill jm-priority-${lead.priority.toLowerCase()}`}>{lead.priority}</span></div><h1>{lead.clientName}</h1><p>{lead.projectType} · {lead.postcode || 'No postcode'}</p><div className="jm-lead-hero-stats"><span><small>Stage</small><strong>{lead.stage}</strong></span><span><small>Selected quote</small><strong>{selectedQuote ? formatGBP(selectedQuote.amount || 0) : 'Not uploaded'}</strong></span><span><small>Files</small><strong>{documents.length}</strong></span></div></div>
      <div className="jm-lead-header-actions"><select value={lead.stage} onChange={(event) => updateLeadStage(id, event.target.value)}>{leadStages.filter((item) => user.role === 'administrator' || !['Won', 'Lost', 'Archived', 'Quote Preparing', 'Quote Sent', 'Negotiation'].includes(item)).map((item) => <option key={item}>{item}</option>)}</select><button className="jm-button" onClick={() => setEdit(!edit)}>{edit ? 'Cancel edit' : 'Edit lead'}</button>{user.role === 'administrator' && !lead.convertedProjectId && <button className="jm-button jm-button--won" onClick={() => setDialog('convert')}><Trophy size={17} />Won job</button>}</div>
    </header>
    {lead.convertedProjectId && <div className="jm-success-banner"><CheckCircle2 size={18} />Converted to a project. <Link to={`/job-manager/projects/${lead.convertedProjectId}`}>Open project</Link></div>}
    <section className="jm-lead-quick-actions"><a href={`tel:${lead.phone}`}><Phone size={18} />Call</a><a href={`mailto:${lead.email}`}><Mail size={18} />Email</a><button onClick={() => setDialog('communication')}><MessageSquarePlus size={18} />Log contact</button><button onClick={() => setDialog('visit')}><CalendarPlus size={18} />Book visit</button>{user.role === 'administrator' && <button onClick={() => setDialog('task')}><Plus size={18} />Add task</button>}</section>

    <div className="jm-lead-detail-grid"><main>
      <section className="jm-panel jm-lead-overview"><header><h2>Lead overview</h2>{edit && <button className="jm-button jm-button--primary" onClick={save} disabled={busy}><Save size={16} />Save</button>}</header>{edit ? <div className="jm-form-grid"><Field label="Client name" value={form.clientName} onChange={(value) => setForm({ ...form, clientName: value })} /><Field label="Phone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} /><Field label="Postcode" value={form.postcode} onChange={(value) => setForm({ ...form, postcode: value })} /><Field label="Address" wide value={form.fullAddress} onChange={(value) => setForm({ ...form, fullAddress: value })} /><Field label="Next action" value={form.nextAction} onChange={(value) => setForm({ ...form, nextAction: value })} /><Field label="Next action due" type="datetime-local" value={form.nextActionDueAt?.slice(0, 16) || ''} onChange={(value) => setForm({ ...form, nextActionDueAt: value })} /><Field label="Enquiry summary" wide textarea value={form.enquirySummary} onChange={(value) => setForm({ ...form, enquirySummary: value })} /><Field label="Internal notes" wide textarea value={form.internalNotes} onChange={(value) => setForm({ ...form, internalNotes: value })} /></div> : <div className="jm-detail-list"><Info label="Contact" value={`${lead.phone || 'No phone'} · ${lead.email || 'No email'}`} /><Info label="Address" value={lead.fullAddress || 'Not added'} /><Info label="Estimated value" value={formatGBP(lead.estimatedValue || 0)} /><Info label="Assigned to" value={users.find((item) => item.id === lead.assignedTo)?.name || 'Unassigned'} /><Info label="Next action" value={lead.nextAction || 'Not set'} /><Info label="Due" value={lead.nextActionDueAt ? formatDate(lead.nextActionDueAt, true) : 'Not set'} /><Info label="Enquiry" value={lead.enquirySummary || 'No summary'} /><Info label="Internal notes" value={lead.internalNotes || 'No notes'} /></div>}</section>
      <LeadFilesPanel lead={lead} quotes={quotes} documents={documents} users={users} storageEnabled={authMode === 'supabase'} canManageQuotes={user.role === 'administrator'} canDelete={(document) => user.role === 'administrator' || document.uploadedBy === user.id} onUploadQuote={(values, file) => uploadLeadQuote(id, values, file)} onUploadFiles={(values, file) => uploadLeadDocument(id, values, file)} onSelectQuote={(quoteId) => selectLeadQuote(id, quoteId)} onDelete={deleteDocument} />
      <section className="jm-panel jm-lead-timeline"><h2>Communications</h2>{communications.length ? communications.map((item) => <article key={item.id}><span>{item.type}</span><div><strong>{item.summary}</strong><p>{item.note}</p><small>{item.direction} · {formatDate(item.occurredAt, true)} · {users.find((entry) => entry.id === item.authorId)?.name}</small>{item.externalLink && <a href={item.externalLink} target="_blank" rel="noreferrer"><ExternalLink size={14} />Open link</a>}</div></article>) : <p className="jm-muted">No communication has been logged yet.</p>}</section>
      <section className="jm-panel"><h2>Tasks & site visits</h2><div className="jm-lead-records">{events.map((event) => <div key={event.id}><CalendarPlus size={18} /><span><strong>{event.title}</strong>{formatDate(event.startDate, true)} · {event.syncStatus === 'not_configured' ? 'Calendar sync not configured' : event.syncStatus}</span></div>)}{tasks.map((task) => <div key={task.id}><CheckCircle2 size={18} /><span><strong>{task.title}</strong>Due {formatDate(task.dueDate)} · {task.priority}</span></div>)}{!events.length && !tasks.length && <p className="jm-muted">No tasks or visits yet.</p>}</div></section>
    </main><aside>
      <section className="jm-panel jm-lead-contact"><h2>Contact & property</h2><a href={`tel:${lead.phone}`}><Phone size={17} />{lead.phone || 'No phone'}</a><a href={`mailto:${lead.email}`}><Mail size={17} />{lead.email || 'No email'}</a><a href={mapsUrl(lead.fullAddress, lead.postcode)} target="_blank" rel="noreferrer"><MapPin size={17} />Open in Maps</a><p>{lead.preferredContactMethod} · {lead.preferredContactTime || 'Any time'}</p></section>
      <section className="jm-panel"><h2>Activity</h2><div className="jm-mini-activity">{activities.slice(0, 8).map((item) => <div key={item.id}><strong>{item.action}</strong><small>{formatDate(item.createdAt, true)}</small></div>)}</div></section>
      {user.role === 'administrator' && !lead.convertedProjectId && <section className="jm-panel jm-lead-controls jm-lead-controls--won"><Trophy size={25} /><h2>Did you win this job?</h2><p>The selected quote and every lead file will move into a new confirmed project.</p><button className="jm-button jm-button--won" onClick={() => setDialog('convert')}><Trophy size={17} />Won job · Create project</button><button className="jm-button jm-button--danger" onClick={() => setDialog('lost')}><XCircle size={17} />Mark lost</button></section>}
    </aside></div>
    {dialog && <LeadDialog type={dialog} lead={lead} quote={selectedQuote} users={users} close={() => setDialog('')} submit={submitDialog} busy={busy} />}
  </>
}

function LeadDialog({ type, lead, quote, users, close, submit, busy }) {
  const today = new Date().toISOString().slice(0, 10)
  const defaults = { communication: { type: 'Call', direction: 'Outbound', summary: '', note: '' }, task: { title: '', dueDate: '', priority: 'Normal', assignedTo: lead.assignedTo }, visit: { startDate: '', endDate: '', notes: '' }, lost: { reason: 'Price', notes: '' }, convert: { title: quote?.projectTitle || `${lead.projectType} - ${lead.clientName}`, startDate: quote?.startDate || today, endDate: quote?.endDate || quote?.startDate || today, assignedTo: lead.assignedTo, contractValue: quote?.amount || lead.estimatedValue || '' } }
  const [form, setForm] = useState(defaults[type]); const titles = { communication: 'Log communication', task: 'Add lead task', visit: 'Book site visit', lost: 'Mark lead as lost', convert: 'Won job · Create project' }
  return <div className="jm-modal-backdrop" onMouseDown={close}><section className="jm-modal jm-lead-dialog" onMouseDown={(event) => event.stopPropagation()}><header><h2>{titles[type]}</h2><button onClick={close}>×</button></header><form onSubmit={(event) => { event.preventDefault(); submit(form) }} className="jm-form-grid">
    {type === 'communication' && <><Select label="Type" value={form.type} options={['Call', 'Email', 'SMS', 'WhatsApp', 'Meeting', 'Note']} onChange={(value) => setForm({ ...form, type: value })} /><Select label="Direction" value={form.direction} options={['Inbound', 'Outbound', 'Internal']} onChange={(value) => setForm({ ...form, direction: value })} /><Field label="Summary" wide required value={form.summary} onChange={(value) => setForm({ ...form, summary: value })} /><Field label="Notes" wide textarea value={form.note} onChange={(value) => setForm({ ...form, note: value })} /></>}
    {type === 'task' && <><Field label="Task" wide required value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><Field label="Due date" type="date" required value={form.dueDate} onChange={(value) => setForm({ ...form, dueDate: value })} /><Select label="Priority" value={form.priority} options={['Low', 'Normal', 'High', 'Urgent']} onChange={(value) => setForm({ ...form, priority: value })} /></>}
    {type === 'visit' && <><Field label="Starts" type="datetime-local" required value={form.startDate} onChange={(value) => setForm({ ...form, startDate: value })} /><Field label="Ends" type="datetime-local" value={form.endDate} onChange={(value) => setForm({ ...form, endDate: value })} /><Field label="Visit notes" wide textarea value={form.notes} onChange={(value) => setForm({ ...form, notes: value })} /></>}
    {type === 'lost' && <><Select label="Reason" value={form.reason} options={['Price', 'No response', 'Chose competitor', 'Timing', 'Not suitable', 'Duplicate', 'Other']} onChange={(value) => setForm({ ...form, reason: value })} /><Field label="Notes" wide textarea value={form.notes} onChange={(value) => setForm({ ...form, notes: value })} /></>}
    {type === 'convert' && <><div className="jm-field-wide jm-won-summary"><Trophy size={21} /><div><strong>{quote ? `Using quote ${quote.reference || ''}` : 'No quote selected'}</strong><span>{quote ? `${formatGBP(quote.amount || 0)} · The quote PDF, files, tasks and visits will move to the project.` : 'The project will use the lead details. You can upload and select a quote first.'}</span></div></div><Field label="Project title" wide required value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><Field label="Start date" type="date" required value={form.startDate} onChange={(value) => setForm({ ...form, startDate: value })} /><Field label="End date" type="date" required value={form.endDate} onChange={(value) => setForm({ ...form, endDate: value })} /><Field label="Contract value (£)" type="number" value={form.contractValue} onChange={(value) => setForm({ ...form, contractValue: value })} /><Select label="Assigned to" value={form.assignedTo || ''} options={users.map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => setForm({ ...form, assignedTo: value })} /></>}
    <footer><button type="button" className="jm-button" onClick={close}>Cancel</button><button className={`jm-button ${type === 'lost' ? 'jm-button--danger' : type === 'convert' ? 'jm-button--won' : 'jm-button--primary'}`} disabled={busy}>{busy ? 'Saving…' : type === 'convert' ? 'Confirm won job' : 'Confirm'}</button></footer>
  </form></section></div>
}

function Info({ label, value }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function Field({ label, wide, textarea, onChange, ...props }) { const Tag = textarea ? 'textarea' : 'input'; return <label className={wide ? 'jm-field-wide' : ''}><span>{label}</span><Tag {...props} onChange={(event) => onChange(event.target.value)} /></label> }
function Select({ label, options, onChange, ...props }) { return <label><span>{label}</span><select {...props} onChange={(event) => onChange(event.target.value)}>{options.map((item) => typeof item === 'string' ? <option key={item}>{item}</option> : <option key={item.value} value={item.value}>{item.label}</option>)}</select></label> }
