import { BarChart3, Columns3, List, Plus, Search, Siren, UserRoundSearch } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useJobManager } from '../context/JobManagerContext'
import { formatDate, formatGBP } from '../utils/format'
import { activeLeadStages, findLeadDuplicates, leadAttention, leadSources, leadStages, projectTypes } from '../utils/leads'
import { MetricCard, PageHeader } from '../components/UI'

const blankLead = { clientName: '', email: '', phone: '', postcode: '', fullAddress: '', projectType: 'Interior Painting', enquirySummary: '', estimatedValue: '', stage: 'New', priority: 'Normal', source: 'Website', assignedTo: '', nextAction: '', nextActionDueAt: '', preferredContactMethod: 'Phone', internalNotes: '' }

export default function LeadsPage() {
  const { data, users, user, saveLead, updateLeadStage } = useJobManager(); const navigate = useNavigate()
  const [view, setView] = useState('overview'); const [search, setSearch] = useState(''); const [stage, setStage] = useState('Active'); const [source, setSource] = useState('All'); const [modal, setModal] = useState(false); const [form, setForm] = useState(blankLead); const [saving, setSaving] = useState(false)
  const leads = user.role === 'administrator' ? data.leads : data.leads.filter((lead) => lead.assignedTo === user.id)
  const filtered = useMemo(() => leads.filter((lead) => {
    const haystack = `${lead.clientName} ${lead.email} ${lead.phone} ${lead.postcode} ${lead.projectType}`.toLowerCase()
    return haystack.includes(search.toLowerCase()) && (stage === 'All' || (stage === 'Active' ? activeLeadStages.includes(lead.stage) : lead.stage === stage)) && (source === 'All' || lead.source === source)
  }), [leads, search, stage, source])
  const now = new Date(); const overdue = leads.filter((lead) => leadAttention(lead, now)); const followUps = leads.filter((lead) => lead.stage === 'Follow-up Due'); const visits = leads.filter((lead) => lead.stage === 'Site Visit Booked'); const quotes = leads.filter((lead) => ['Quote Preparing', 'Quote Sent'].includes(lead.stage)); const won = leads.filter((lead) => lead.stage === 'Won')
  const duplicates = findLeadDuplicates(leads, form)
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const id = await saveLead(form); setModal(false); navigate(`/job-manager/leads/${id}`) } finally { setSaving(false) } }

  return <>
    <PageHeader eyebrow="Enquiries & opportunities" title="Leads" description="Track every enquiry from first contact through to a confirmed project." action={user.role === 'administrator' ? <button className="jm-button jm-button--primary" onClick={() => setModal(true)}><Plus size={18} />Add lead</button> : null} />
    <section className="jm-metrics jm-lead-metrics"><MetricCard icon={UserRoundSearch} label="Active leads" value={leads.filter((l) => activeLeadStages.includes(l.stage)).length} detail="Open opportunities" tone="green" /><MetricCard icon={Siren} label="Needs attention" value={overdue.length} detail="Action due or overdue" tone="red" /><MetricCard icon={Columns3} label="Site visits" value={visits.length} detail="Currently booked" tone="blue" /><MetricCard icon={BarChart3} label="Won value" value={formatGBP(won.reduce((sum, l) => sum + Number(l.estimatedValue || 0), 0))} detail={`${won.length} converted`} tone="orange" /></section>
    <section className="jm-panel jm-leads-toolbar"><div className="jm-view-tabs"><button className={view === 'overview' ? 'active' : ''} onClick={() => setView('overview')}>Overview</button><button className={view === 'pipeline' ? 'active' : ''} onClick={() => setView('pipeline')}><Columns3 size={16} />Pipeline</button><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><List size={16} />List</button><button className={view === 'analytics' ? 'active' : ''} onClick={() => setView('analytics')}><BarChart3 size={16} />Analytics</button></div><div className="jm-lead-filters"><label><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, phone or postcode" /></label><select value={stage} onChange={(e) => setStage(e.target.value)}><option>Active</option><option>All</option>{leadStages.map((item) => <option key={item}>{item}</option>)}</select><select value={source} onChange={(e) => setSource(e.target.value)}><option>All</option>{leadSources.map((item) => <option key={item}>{item}</option>)}</select></div></section>
    {view === 'overview' && <div className="jm-dashboard-columns"><LeadSection title="Follow-ups due" leads={followUps} /><LeadSection title="Overdue actions" leads={overdue} /><LeadSection title="Site visits booked" leads={visits} /><LeadSection title="Quotes in progress" leads={quotes} /></div>}
    {view === 'pipeline' && <div className="jm-lead-pipeline">{activeLeadStages.map((column) => <section key={column}><header><strong>{column}</strong><span>{filtered.filter((lead) => lead.stage === column).length}</span></header>{filtered.filter((lead) => lead.stage === column).map((lead) => <LeadCard key={lead.id} lead={lead} users={users} onStage={updateLeadStage} />)}</section>)}</div>}
    {view === 'list' && <section className="jm-panel jm-lead-table"><table><thead><tr><th>Lead</th><th>Stage</th><th>Next action</th><th>Source</th><th>Value</th></tr></thead><tbody>{filtered.map((lead) => <tr key={lead.id} onClick={() => navigate(`/job-manager/leads/${lead.id}`)}><td><strong>{lead.clientName}</strong><small>{lead.projectType} · {lead.postcode}</small></td><td><span className="jm-lead-stage">{lead.stage}</span></td><td>{lead.nextAction || 'Not set'}<small>{lead.nextActionDueAt ? formatDate(lead.nextActionDueAt, true) : ''}</small></td><td>{lead.source}</td><td>{formatGBP(lead.estimatedValue || 0)}</td></tr>)}</tbody></table></section>}
    {view === 'analytics' && <section className="jm-panel jm-lead-analytics"><h2>Lead performance</h2><div className="jm-analytics-grid"><div><strong>{leads.length ? Math.round((won.length / leads.length) * 100) : 0}%</strong><span>Overall win rate</span></div><div><strong>{formatGBP(leads.reduce((sum, l) => sum + Number(l.estimatedValue || 0), 0))}</strong><span>Total pipeline value</span></div><div><strong>{leads.filter((l) => l.source === 'Bark').reduce((sum, l) => sum + Number(l.barkCreditsSpent || 0), 0)}</strong><span>Bark credits spent</span></div></div><h3>Source performance</h3>{leadSources.map((item) => { const group = leads.filter((lead) => lead.source === item); if (!group.length) return null; return <div className="jm-source-row" key={item}><span>{item}</span><strong>{group.length} leads · {group.filter((l) => l.stage === 'Won').length} won</strong></div> })}</section>}
    {modal && <div className="jm-modal-backdrop" onMouseDown={() => setModal(false)}><section className="jm-modal jm-lead-modal" onMouseDown={(e) => e.stopPropagation()}><header><div><p className="jm-eyebrow">New enquiry</p><h2>Add lead</h2></div><button onClick={() => setModal(false)}>×</button></header><form onSubmit={submit} className="jm-form-grid"><Field label="Client name" required value={form.clientName} onChange={(v) => setForm({ ...form, clientName: v })} /><Field label="Phone" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })} /><Field label="Email" type="email" value={form.email} onChange={(v) => setForm({ ...form, email: v })} /><Field label="Postcode" value={form.postcode} onChange={(v) => setForm({ ...form, postcode: v })} /><Field label="Full address" wide value={form.fullAddress} onChange={(v) => setForm({ ...form, fullAddress: v })} /><Select label="Project type" value={form.projectType} options={projectTypes} onChange={(v) => setForm({ ...form, projectType: v })} /><Select label="Source" value={form.source} options={leadSources} onChange={(v) => setForm({ ...form, source: v })} /><Select label="Priority" value={form.priority} options={['Low','Normal','High','Urgent']} onChange={(v) => setForm({ ...form, priority: v })} /><Select label="Assigned to" value={form.assignedTo} options={users.map((u) => ({ value: u.id, label: u.name }))} onChange={(v) => setForm({ ...form, assignedTo: v })} /><Field label="Estimated value (£)" type="number" value={form.estimatedValue} onChange={(v) => setForm({ ...form, estimatedValue: v })} /><Field label="Next action due" type="datetime-local" value={form.nextActionDueAt} onChange={(v) => setForm({ ...form, nextActionDueAt: v })} /><Field label="Enquiry summary" wide textarea value={form.enquirySummary} onChange={(v) => setForm({ ...form, enquirySummary: v })} />{duplicates.length > 0 && <p className="jm-duplicate-warning">Possible duplicate: {duplicates.map((item) => item.clientName).join(', ')}. You can still save this lead.</p>}<footer><button type="button" className="jm-button" onClick={() => setModal(false)}>Cancel</button><button className="jm-button jm-button--primary" disabled={saving}>{saving ? 'Saving…' : 'Save lead'}</button></footer></form></section></div>}
  </>
}

function LeadSection({ title, leads }) { return <section className="jm-panel jm-lead-section"><h2>{title}</h2>{leads.length ? leads.slice(0, 5).map((lead) => <Link key={lead.id} to={`/job-manager/leads/${lead.id}`}><div><strong>{lead.clientName}</strong><span>{lead.projectType} · {lead.postcode}</span></div><small>{lead.nextActionDueAt ? formatDate(lead.nextActionDueAt, true) : lead.stage}</small></Link>) : <p className="jm-muted">Nothing here right now.</p>}</section> }
function LeadCard({ lead, users, onStage }) { return <article className={`jm-lead-card jm-priority-${lead.priority.toLowerCase()}`}><Link to={`/job-manager/leads/${lead.id}`}><small>{lead.source} · {lead.priority}</small><strong>{lead.clientName}</strong><span>{lead.projectType}</span><span>{lead.postcode} · {formatGBP(lead.estimatedValue || 0)}</span><p>{lead.nextAction || 'No next action set'}</p></Link><select value={lead.stage} onChange={(e) => onStage(lead.id, e.target.value)} aria-label={`Change stage for ${lead.clientName}`}>{leadStages.map((item) => <option key={item}>{item}</option>)}</select><small>{users.find((u) => u.id === lead.assignedTo)?.name || 'Unassigned'}</small></article> }
function Field({ label, wide, textarea, onChange, ...props }) { const Tag = textarea ? 'textarea' : 'input'; return <label className={wide ? 'jm-field-wide' : ''}><span>{label}</span><Tag {...props} onChange={(e) => onChange(e.target.value)} /></label> }
function Select({ label, options, onChange, ...props }) { return <label><span>{label}</span><select {...props} onChange={(e) => onChange(e.target.value)}><option value="">Unassigned</option>{options.map((item) => typeof item === 'string' ? <option key={item}>{item}</option> : <option key={item.value} value={item.value}>{item.label}</option>)}</select></label> }
