import { CalendarDays, ChevronDown, Clipboard, Mail, MapPin, MessageCircle, Navigation, Phone, UserRound } from 'lucide-react'
import { useState } from 'react'
import { communicationService, googleCalendarService, locationService } from '../services/integrationServices'

export function ClientInformationCard({ client, project }) {
  const [copied, setCopied] = useState(false); const [open, setOpen] = useState(() => !window.matchMedia('(max-width: 760px)').matches)
  const copy = async () => { await communicationService.copyClientDetails(client); setCopied(true); setTimeout(() => setCopied(false), 1600) }
  return <section className={`jm-detail-card jm-secondary-card ${open ? 'open' : ''}`}><button className="jm-secondary-heading" onClick={() => setOpen((value) => !value)} aria-expanded={open}><span><UserRound size={18} />Client information</span><ChevronDown size={17} /></button><div className="jm-secondary-content"><div className="jm-client-profile"><span>{client.name[0]}</span><div><strong>{client.name}</strong><a href={communicationService.phoneUrl(client)}>{client.phone}</a><a href={communicationService.emailUrl(client, project)}>{client.email}</a></div></div><div className="jm-contact-details"><div><span>Preferred contact</span><strong>{client.preferredContact || 'Not set'}</strong></div><div><span>Best contact time</span><strong>{client.bestContactTime || 'Not set'}</strong></div>{client.emergencyContact && <div><span>Emergency contact</span><strong>{client.emergencyContact}</strong></div>}</div><div className="jm-inline-actions"><a href={communicationService.phoneUrl(client)}><Phone size={15} />Call</a><a href={communicationService.emailUrl(client, project)}><Mail size={15} />Email</a><a href={communicationService.whatsappUrl(client, project)} target="_blank" rel="noreferrer"><MessageCircle size={15} />WhatsApp</a><button onClick={copy}><Clipboard size={15} />{copied ? 'Copied' : 'Copy details'}</button></div></div></section>
}

export function LocationCard({ project }) {
  const [copied, setCopied] = useState(false); const [open, setOpen] = useState(() => !window.matchMedia('(max-width: 760px)').matches)
  const copy = async () => { await locationService.copyAddress(project); setCopied(true); setTimeout(() => setCopied(false), 1600) }
  return <section className={`jm-detail-card jm-secondary-card ${open ? 'open' : ''}`}><button className="jm-secondary-heading" onClick={() => setOpen((value) => !value)} aria-expanded={open}><span><MapPin size={18} />Location</span><ChevronDown size={17} /></button><div className="jm-secondary-content"><a className="jm-location-address" href={locationService.mapsUrl(project)} target="_blank" rel="noreferrer"><strong>{project.address}</strong><span>{project.postcode}</span></a><div className="jm-contact-details"><div><span>Parking</span><strong>{project.parkingNotes || 'Not added'}</strong></div><div><span>Access</span><strong>{project.accessNotes || 'Not added'}</strong></div><div><span>Key status</span><strong>{project.keyStatus || 'Not set'}</strong></div><div><span>What3Words</span><strong className="jm-muted-value">Future integration</strong></div></div><div className="jm-inline-actions"><a href={locationService.mapsUrl(project)} target="_blank" rel="noreferrer"><Navigation size={15} />Google Maps</a><button onClick={copy}><Clipboard size={15} />{copied ? 'Copied' : 'Copy address'}</button><a href={googleCalendarService.projectUrl(project)} target="_blank" rel="noreferrer"><CalendarDays size={15} />Calendar</a></div></div></section>
}
