import { Download, ExternalLink, File, FileCheck2, FileImage, FolderOpen, ImagePlus, Maximize2, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { formatDate } from '../utils/format'

const documentGroups = ['Quotation', 'Invoice', 'Payment schedule', 'Photos', 'Contract', 'Certificate', 'Google Drive folder', 'Other']
const documentIcon = (type) => type === 'Photos' ? FileImage : type.includes('Drive') ? FolderOpen : type === 'Certificate' ? FileCheck2 : File

export function DocumentsSection({ documents, users, canDelete, onDelete }) {
  const groups = useMemo(() => documentGroups.map((type) => ({ type, items: documents.filter((document) => document.type.toLowerCase() === type.toLowerCase()) })).filter((group) => group.items.length), [documents])
  return <section className="jm-detail-card"><div className="jm-card-heading"><div><h2>Documents</h2><p>{documents.length} linked file{documents.length === 1 ? '' : 's'}</p></div><span>Grouped by type</span></div>{groups.length ? <div className="jm-document-groups">{groups.map((group) => <div key={group.type}><h3>{group.type}</h3>{group.items.map((document) => { const Icon = documentIcon(document.type); const uploader = users.find((user) => user.id === document.uploadedBy); return <article key={document.id}><span className="jm-document-icon"><Icon size={18} /></span><div><strong>{document.name}</strong><small>{formatDate(document.createdAt)} · {uploader?.name || 'Ictinus'}</small></div><a href={document.url} target="_blank" rel="noreferrer" aria-label="Open document"><ExternalLink size={15} /></a><a href={document.url} download aria-label="Download document"><Download size={15} /></a>{canDelete && <button onClick={() => onDelete(document.id)} aria-label="Delete document"><Trash2 size={15} /></button>}</article> })}</div>)}</div> : <p className="jm-empty-copy">No documents linked yet.</p>}</section>
}

export function PhotoGallery({ photos, users, canDelete, onDelete, onAdd }) {
  const [stage, setStage] = useState('Before'); const [preview, setPreview] = useState(null); const [adding, setAdding] = useState(false)
  const filtered = photos.filter((photo) => photo.stage === stage)
  const submit = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); onAdd(values); event.currentTarget.reset(); setAdding(false); setStage(values.stage) }
  return <section className="jm-detail-card jm-photo-section"><div className="jm-card-heading"><div><h2>Photo gallery</h2><p>{photos.length} project photo{photos.length === 1 ? '' : 's'}</p></div><button className="jm-button jm-button--small jm-button--secondary" onClick={() => setAdding((value) => !value)}><ImagePlus size={15} />Add photo</button></div><div className="jm-photo-tabs">{['Before', 'Progress', 'Completed'].map((item) => <button key={item} className={stage === item ? 'active' : ''} onClick={() => setStage(item)}>{item}<span>{photos.filter((photo) => photo.stage === item).length}</span></button>)}</div>{adding && <form className="jm-photo-form" onSubmit={submit}><select name="stage" defaultValue={stage}><option>Before</option><option>Progress</option><option>Completed</option></select><input name="title" placeholder="Photo title" required /><input name="url" type="url" placeholder="Image URL for this version" required /><button className="jm-button jm-button--primary" type="submit">Add</button></form>}<div className="jm-photo-grid">{filtered.map((photo) => <article key={photo.id}><button className="jm-photo-open" onClick={() => setPreview(photo)}><img src={photo.url} alt={photo.title} /><span><Maximize2 size={16} /></span></button><div><strong>{photo.title}</strong><small>{formatDate(photo.createdAt)} · {users.find((user) => user.id === photo.uploadedBy)?.name}</small></div>{canDelete && <button className="jm-photo-delete" onClick={() => onDelete(photo.id)} aria-label="Delete photo"><Trash2 size={15} /></button>}</article>)}{filtered.length === 0 && <p className="jm-empty-copy">No {stage.toLowerCase()} photos yet.</p>}</div>{preview && <div className="jm-photo-preview" role="dialog" aria-modal="true" aria-label={preview.title} onClick={() => setPreview(null)}><button aria-label="Close preview"><X size={24} /></button><img src={preview.url} alt={preview.title} /><div><strong>{preview.title}</strong><span>{preview.stage} · {formatDate(preview.createdAt)}</span></div></div>}</section>
}
